# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=50)),
                ('n_path', models.CharField(max_length=3000)),
                ('n_year', models.IntegerField()),
                ('n_upload_date_time', models.DateTimeField()),
                ('n_average_rating', models.FloatField()),
            ],
        ),
    ]
