# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-04 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='id',
        ),
        migrations.AddField(
            model_name='notes',
            name='n_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
