# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190104_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_logo', models.CharField(max_length=3000)),
                ('u_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'Notes'},
        ),
        migrations.AddField(
            model_name='notes',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.University'),
            preserve_default=False,
        ),
    ]
