# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190105_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='u_id',
        ),
        migrations.AddField(
            model_name='notes',
            name='n_university',
            field=models.ManyToManyField(to='users.University'),
        ),
    ]
