# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190106_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='n_university',
        ),
        migrations.AddField(
            model_name='notes',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.University'),
            preserve_default=False,
        ),
    ]
