# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190106_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_pic', models.CharField(max_length=3000)),
                ('p_fname', models.CharField(max_length=20)),
                ('p_lname', models.CharField(max_length=20)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.University')),
            ],
            options={
                'verbose_name_plural': 'Professors',
            },
        ),
    ]
