# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_department_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='d_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='p_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
            preserve_default=False,
        ),
    ]
