# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190106_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_title', models.CharField(max_length=50)),
                ('n_path', models.CharField(max_length=3000)),
                ('n_year', models.IntegerField()),
                ('n_upload_date_time', models.DateTimeField()),
                ('n_average_rating', models.FloatField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
            ],
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(max_length=4)),
                ('n_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_pic', models.CharField(max_length=3000)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pass', models.CharField(max_length=30)),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='p_id',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='u_id',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
        migrations.AddField(
            model_name='rating',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='notetag',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tag'),
        ),
        migrations.AddField(
            model_name='note',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Professor'),
        ),
        migrations.AddField(
            model_name='note',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.University'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='n_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='n_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='n_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Note'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
