# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190106_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='n_id',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
